fand now checks to see if the config file exists and is valid

diff --git a/fand b/fand
--- a/fand
+++ b/fand
@@ -15,8 +15,33 @@ SLEEP=180
 
 #finds the config file
 WORKINGDIR="$(dirname "$0")"
+if [ ! -f "$WORKINGDIR/settings" ]; then
+    echo "ERROR: Could not access settings file. Check your $WORKINGDIR/settings file."
+    exit 1
+fi
+
 #parses the config file
 source "$WORKINGDIR/settings"
+
+#makes sure the config file is valid
+re='^[0-9]+$'
+if ! [[ $MAX =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $SEVEN =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $SIX =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $FIVE =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $FOUR =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $THREE =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $TWO =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+elif ! [[ $SLEEP =~ $re ]] ; then
+   echo "Error: Bad Config File. Check $WORKINGDIR/settings" >&2; exit 1
+fi
 
 #finds number of cpu cores
 NUMCORES=$(grep -c ^processor /proc/cpuinfo)
@@ -44,7 +69,7 @@ while true; do
         HIGHTEMP=$CURRTEMP
       fi
     done
-  else
+  elif (($MODE == MAX)); then
     for x in `seq 0 $(($NUMCORES - 1))`; do
       CURRTEMP=$(($(cat /sys/class/thermal/thermal_zone$x/temp) / 1000))
       if (($HIGHTEMP == 0)); then
@@ -53,6 +78,9 @@ while true; do
         HIGHTEMP=$(($(($CURRTEMP + $HIGHTEMP)) / 2))
       fi
     done
+  #if the mode is neither MAX or AVG, the config file is broken
+  else
+    echo "Error: Bad Config File. Check $WORKINGDIR/settings"
   fi
   
   #check config files and take action
